version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: plastcontrol_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: plastic_factory_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Opcional: Interfaz visual de base de datos
  pgadmin:
    image: dpage/pgadmin4
    container_name: plastcontrol_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@plastcontrol.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
